# Generated by Django 6.0.3 on 2026-03-24 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('verified_clean', models.IntegerField(default=0)),
                ('verification_failed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('last_task_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('verified_clean', 'Verified Clean'), ('verification_failed', 'Verification Failed'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='cleaning_proofs/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='cleaning_proofs/after/')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_type', models.CharField(choices=[('SWEEPING', 'Sweeping'), ('ROAD_REPAIR', 'Road Repair'), ('WATER_MAINTENANCE', 'Water Maintenance'), ('GARBAGE_COLLECTION', 'Garbage Collection'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=20)),
                ('image', models.ImageField(upload_to='task_proofs/')),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('watermark_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='operations.task')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo_time', models.DateTimeField()),
                ('after_photo_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('sla_threshold_minutes', models.IntegerField(default=120)),
                ('sla_met', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='operations.task')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_prediction', models.CharField(blank=True, max_length=50)),
                ('before_confidence', models.FloatField(blank=True, null=True)),
                ('before_class_scores', models.JSONField(blank=True, null=True)),
                ('after_prediction', models.CharField(blank=True, max_length=50)),
                ('after_confidence', models.FloatField(blank=True, null=True)),
                ('after_class_scores', models.JSONField(blank=True, null=True)),
                ('cleanup_successful', models.BooleanField(blank=True, null=True)),
                ('cleanup_confidence', models.FloatField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified_clean', 'Verified Clean'), ('incomplete', 'Incomplete'), ('error', 'Error')], default='pending', max_length=30)),
                ('recommendation_message', models.TextField(blank=True)),
                ('model_version', models.CharField(default='google/vit-base-patch16-224', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaning_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='operations.cleaningtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['worker', 'status'], name='operations__worker__51d457_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['task_id'], name='operations__task_id_597246_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='operations__assigne_ea1b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id'], name='operations__task_id_07c8b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskproof',
            unique_together={('task', 'proof_type')},
        ),
    ]
