# Generated by Django 5.2 on 2026-03-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('verified_clean', models.IntegerField(default=0)),
                ('verification_failed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('last_task_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_type', models.CharField(choices=[('SWEEPING', 'Sweeping'), ('ROAD_REPAIR', 'Road Repair'), ('WATER_MAINTENANCE', 'Water Maintenance'), ('GARBAGE_COLLECTION', 'Garbage Collection'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=20)),
                ('image', models.ImageField(upload_to='task_proofs/')),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('watermark_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='operations.task')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo_time', models.DateTimeField()),
                ('after_photo_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('sla_threshold_minutes', models.IntegerField(default=120)),
                ('sla_met', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='operations.task')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('verified_clean', 'Verified Clean'), ('incomplete', 'Incomplete'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('cleanup_confidence', models.FloatField(blank=True, null=True)),
                ('recommendation_message', models.TextField(blank=True)),
                ('model_version', models.CharField(default='vit-base-patch16-224', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='operations.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='operations__assigne_ea1b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id'], name='operations__task_id_07c8b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskproof',
            unique_together={('task', 'proof_type')},
        ),
    ]
