# Generated by Django 5.2 on 2026-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproof',
            name='worker_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='task_proofs/selfies/'),
        ),
    ]
