# Generated by Django 5.2 on 2026-03-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_taskproof_worker_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskproof',
            name='proof_type',
            field=models.CharField(choices=[('BEFORE', 'Before'), ('DURING', 'During'), ('AFTER', 'After')], max_length=20),
        ),
    ]
