# Generated by Django 5.2 on 2026-03-24 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_taskproof_proof_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproof',
            name='image_blur_detection',
            field=models.BooleanField(default=False, help_text='True if image is blurry'),
        ),
        migrations.AddField(
            model_name='taskproof',
            name='image_contrast_level',
            field=models.FloatField(default=0.0, help_text='Image contrast level'),
        ),
        migrations.AddField(
            model_name='taskproof',
            name='image_quality_score',
            field=models.IntegerField(default=0, help_text='Image quality score 0-100'),
        ),
        migrations.CreateModel(
            name='TaskCompletionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_analysis_text', models.TextField(help_text='Time Analysis: actual duration vs SLA threshold')),
                ('location_analysis_text', models.TextField(help_text='Location: GPS validation and distance between photos')),
                ('quality_analysis_text', models.TextField(help_text='Task Quality: image quality scores and similarity percentage')),
                ('sla_analysis_text', models.TextField(help_text='SLA Performance: met/not met and performance percentage')),
                ('recommendations_text', models.TextField(help_text='Recommendations: suggestions based on metrics')),
                ('actual_duration_minutes', models.IntegerField(help_text='Actual time taken to complete task')),
                ('sla_threshold_minutes', models.IntegerField(help_text='Expected time for task completion')),
                ('gps_distance_meters', models.FloatField(help_text='Distance between before and after GPS locations')),
                ('image_similarity_percentage', models.FloatField(help_text='Visual similarity score 0-100')),
                ('before_image_quality_score', models.IntegerField(default=0)),
                ('after_image_quality_score', models.IntegerField(default=0)),
                ('sla_met', models.BooleanField(default=False)),
                ('comparison_datetime', models.DateTimeField(auto_now_add=True, help_text='When comparison was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_report', to='operations.task')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='operations__task_id_558144_idx'), models.Index(fields=['worker', 'created_at'], name='operations__worker__d843f8_idx')],
            },
        ),
    ]
