# Generated by Django 5.2 on 2026-03-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDustbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('max_capacity_liters', models.IntegerField(default=50)),
                ('alert_threshold', models.FloatField(default=0.8)),
                ('location_name', models.CharField(max_length=255)),
                ('maintenance_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('FAULTY', 'Faulty'), ('SCHEDULED_MAINTENANCE', 'Scheduled Maintenance')], default='OPERATIONAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('gps_tracker', 'GPS Tracker'), ('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('motion', 'Motion Sensor'), ('camera', 'Camera'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot_assets.iotdevice')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_volume', models.FloatField()),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('sms_recipient_numbers', models.JSONField()),
                ('twilio_message_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('dustbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot_assets.smartdustbin')),
            ],
        ),
        migrations.CreateModel(
            name='BinVolumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_liters', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('sensor_accuracy', models.FloatField(blank=True, null=True)),
                ('dustbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_data', to='iot_assets.smartdustbin')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['dustbin', '-timestamp'], name='iot_assets__dustbin_1aad97_idx')],
            },
        ),
    ]
