# Generated by Django 5.2 on 2026-03-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=100, unique=True)),
                ('zone_name', models.CharField(max_length=255)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('radius_km', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_in_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('selfie_url', models.URLField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('is_geofence_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_lat', models.FloatField()),
                ('clock_in_lon', models.FloatField()),
                ('clock_in_time', models.DateTimeField(auto_now_add=True)),
                ('is_within_geofence', models.BooleanField(default=False)),
                ('vpn_detected', models.BooleanField(default=False)),
                ('dev_mode_detected', models.BooleanField(default=False)),
                ('mock_location_detected', models.BooleanField(default=False)),
                ('attendance_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, help_text='Reason for rejection if status is REJECTED', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
                ('assigned_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workzone')),
            ],
            options={
                'ordering': ['-clock_in_time'],
                'indexes': [models.Index(fields=['user', 'clock_in_time'], name='attendance__user_id_052f0d_idx'), models.Index(fields=['attendance_status'], name='attendance__attenda_6043e6_idx')],
            },
        ),
    ]
