# Generated by Django 6.0.3 on 2026-03-24 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_in_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('selfie_url', models.URLField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('is_geofence_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
