# Generated by Django 5.2 on 2026-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=100, unique=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('complaint_type', models.CharField(choices=[('MISSING_COLLECTION', 'Missing Collection'), ('INCOMPLETE_WORK', 'Incomplete Work'), ('POOR_SERVICE', 'Poor Service'), ('OTHER', 'Other')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='reports_cit_status_7fbdf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeatmapDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_lat', models.FloatField()),
                ('grid_lon', models.FloatField()),
                ('complaint_density', models.IntegerField(default=0)),
                ('avg_task_completion_delay_minutes', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('grid_lat', 'grid_lon', 'generated_at')},
            },
        ),
    ]
