<<<<<<< HEAD
# Generated by Django 5.2 on 2026-03-24 15:02
=======
# Generated by Django 6.0.3 on 2026-03-24 12:39
>>>>>>> dc4d18bafcd4ef40f049d51a2ce3d7f6304db71e

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('GARBAGE_TRUCK', 'Garbage Truck'), ('MAINTENANCE_VEHICLE', 'Maintenance Vehicle')], max_length=50)),
                ('current_status', models.CharField(choices=[('IDLE', 'Idle'), ('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance')], default='IDLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_stop_id', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('alert_sent_to_admin', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GpsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='fleet_gpslo_vehicle_55f711_idx')],
=======
                ('registration', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
>>>>>>> dc4d18bafcd4ef40f049d51a2ce3d7f6304db71e
            },
        ),
    ]
